<?php

return [
    'servers' => [
        ['value' => '0', 'slug' => '', 'title' => 'Nhập ID máy chủ', 'label' => 'Nhập ID máy chủ'],
        ['value' => 's33', 'slug' => 's33', 'title' => 'S33', 'label' => 'S33'],
        ['value' => 's32', 'slug' => 's32', 'title' => 'S32', 'label' => 'S32'],
        ['value' => 's31', 'slug' => 's31', 'title' => 'S31', 'label' => 'S31'],
        ['value' => 's30', 'slug' => 's30', 'title' => 'S30', 'label' => 'S30'],
        ['value' => 's29', 'slug' => 's29', 'title' => 'S29', 'label' => 'S29'],
        ['value' => 's28', 'slug' => 's28', 'title' => 'S28', 'label' => 'S28'],
        ['value' => 's27', 'slug' => 's27', 'title' => 'S27', 'label' => 'S27'],
        ['value' => 's26', 'slug' => 's26', 'title' => 'S26', 'label' => 'S26'],
        ['value' => 's25', 'slug' => 's25', 'title' => 'S25', 'label' => 'S25'],
        ['value' => 's24', 'slug' => 's24', 'title' => 'S24', 'label' => 'S24'],
        ['value' => 's23', 'slug' => 's23', 'title' => 'S23', 'label' => 'S23'],
        ['value' => 's22', 'slug' => 's22', 'title' => 'S22', 'label' => 'S22'],
        ['value' => 's21', 'slug' => 's21', 'title' => 'S21', 'label' => 'S21'],
        ['value' => 's20', 'slug' => 's20', 'title' => 'S20', 'label' => 'S20'],
        ['value' => 's19', 'slug' => 's19', 'title' => 'S19', 'label' => 'S19'],
        ['value' => 's18', 'slug' => 's18', 'title' => 'S18', 'label' => 'S18'],
        ['value' => 's17', 'slug' => 's17', 'title' => 'S17', 'label' => 'S17'],
        ['value' => 's16', 'slug' => 's16', 'title' => 'S16', 'label' => 'S16'],
        ['value' => 's15', 'slug' => 's15', 'title' => 'S15', 'label' => 'S15'],
        ['value' => 's14', 'slug' => 's14', 'title' => 'S14', 'label' => 'S14'],
        ['value' => 's13', 'slug' => 's13', 'title' => 'S13', 'label' => 'S13'],
        ['value' => 's12', 'slug' => 's12', 'title' => 'S12', 'label' => 'S12'],
        ['value' => 's11', 'slug' => 's11', 'title' => 'S11', 'label' => 'S11'],
        ['value' => 's10', 'slug' => 's10', 'title' => 'S10', 'label' => 'S10'],
        ['value' => 's9', 'slug' => 's9', 'title' => 'S9', 'label' => 'S9'],
        ['value' => 's8', 'slug' => 's8', 'title' => 'S8', 'label' => 'S8'],
        ['value' => 's7', 'slug' => 's7', 'title' => 'S7', 'label' => 'S7'],
        ['value' => 's6', 'slug' => 's6', 'title' => 'S6', 'label' => 'S6'],
        ['value' => 's5', 'slug' => 's5', 'title' => 'S5', 'label' => 'S5'],
        ['value' => 's4', 'slug' => 's4', 'title' => 'S4', 'label' => 'S4'],
        ['value' => 's3', 'slug' => 's3', 'title' => 'S3', 'label' => 'S3'],
        ['value' => 's2', 'slug' => 's2', 'title' => 'S2', 'label' => 'S2'],
        ['value' => 's1', 'slug' => 's1', 'title' => 'S1', 'label' => 'S1'],
    ],

    'code_types' => [
        [
            'id' => 1,
            'label' => '-- Chọn loại code --',
            'code' => '0',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.1',
        ],
        [
            'id' => 2,
            'label' => 'Code Tân Thủ',
            'code' => '0',
            'default_code' => 'HAITACMANHNHAT-TANTHU',
            'table_view' => 'partials.giftcode.tables.2',
        ],
        [
            'id' => 3,
            'label' => 'HĐ LV 10',
            'code' => '27197',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.3',
        ],
        [
            'id' => 4,
            'label' => 'HĐ LV 20',
            'code' => '27199',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.4',
        ],
        [
            'id' => 5,
            'label' => 'HĐ LV 40',
            'code' => '27201',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.5',
        ],
        [
            'id' => 7,
            'label' => 'HĐ LV 60',
            'code' => '27203',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.7',
        ],
        [
            'id' => 9,
            'label' => 'HĐ LV 80',
            'code' => '27205',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.9',
        ],
        [
            'id' => 11,
            'label' => 'HĐ LV 100',
            'code' => '27207',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.11',
        ],
        [
            'id' => 13,
            'label' => 'HĐ LV 110',
            'code' => '27209',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.13',
        ],
        [
            'id' => 15,
            'label' => 'HĐ LV 120',
            'code' => '27211',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.15',
        ],
        [
            'id' => 16,
            'label' => 'HĐ LV 130',
            'code' => '27213',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.16',
        ],
        [
            'id' => 17,
            'label' => 'HĐ LV 140',
            'code' => '27215',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.17',
        ],
        [
            'id' => 18,
            'label' => 'HĐ LV 150',
            'code' => '27217',
            'default_code' => null,
            'table_view' => 'partials.giftcode.tables.18',
        ],
    ],
];
